### ISSUE TITLE
mocha tests breaking

### ISSUE THREAD

**Issue by SammySteiner** [learn-co-curriculum/react-component-mounting-and-unmounting-lab#10]
Running tests with Learn works, but running them with mocha will not pass the third test. The error seems to come from line 31 in index-test.js. The line reads `wrapper.unmount();`

The error message in mocha is: 
Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.

**Comment by gj** [comment]
Thanks for pointing this out @SammySteiner !
